### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Stunt0265** [ntnj/tunwg#1]
When trying to self host and installing using the:

go install https://github.com/ntnj/tunwg/tunwgs
TUNWG_API=example.com TUNWG_IP=<ip-of-server> TUNWG_PORT=<wireguard-port> tunwgs

I'm getting several errors like:

malformed import path "https:/github.com/ntnj/tunwg/tunwgs": invalid char ':'

**Comment by ntnj** [comment]
The command is `go install github.com/ntnj/tunwg/tunwgs@latest`.

I've updated it in README, which mentioned the incorrect command before. Thanks for trying it out. Let me know if you face any other issues.
