### ISSUE TITLE
Connection to server fails

### ISSUE THREAD

**Issue by fadiaburaid** [ntnj/tunwg#5]
Thank you for offering tunneling service free of charge.
I have used the service for the past 2 weeks and it was stable.
However, since yesterday I am getting this error when I try to connect, and it just keeps trying to connect.

> 2023/07/14 08:49:17 tunwg: initiating handshake to server

**Comment by ntnj** [comment]
Hi, 
Is the issue still happening? The server should be up. It sometimes goes down briefly for updates and such.
Can you try adding `TUNWG_RELAY=true` to environment if your firewall is blocking UDP packets?

**Comment by fadiaburaid** [comment]
I have tried you suggestion and it is still not working. Your server IP might have been blocked by GFW because I am in China.
